// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8jos-KjDkbomwRKlBcJoPKdSmA705owg',
    appId: '1:952922104031:web:42332d9b84fd800a3a096a',
    messagingSenderId: '952922104031',
    projectId: 'rehab-app-81d83',
    authDomain: 'rehab-app-81d83.firebaseapp.com',
    storageBucket: 'rehab-app-81d83.appspot.com',
    measurementId: 'G-9S80M8CQ7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADuDKOie6ogRE5QRWwldd4M553tEEEgkM',
    appId: '1:952922104031:android:43c92932a200f8de3a096a',
    messagingSenderId: '952922104031',
    projectId: 'rehab-app-81d83',
    storageBucket: 'rehab-app-81d83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB346bjSjv_5jNSIFPjMrPP2mGLopbZT34',
    appId: '1:952922104031:ios:b95b066b8be55c193a096a',
    messagingSenderId: '952922104031',
    projectId: 'rehab-app-81d83',
    storageBucket: 'rehab-app-81d83.appspot.com',
    iosClientId: '952922104031-qo10iktfdqecg2bslk3384m625ueuevp.apps.googleusercontent.com',
    iosBundleId: 'com.flutterassi.rehabApp',
  );
}
